# Generated by Django 4.2.29 on 2026-04-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_teams_remove_player_date_of_birth_player_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
