# Generated by Django 4.2.29 on 2026-05-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_delete_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='headshot_url',
            field=models.URLField(blank=True),
        ),
    ]
