# Generated by Django 4.2.29 on 2026-05-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_remove_player_age_player_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='external_player_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
