# Generated by Django 4.2.29 on 2026-03-21 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='last_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='coach',
            name='role',
            field=models.CharField(choices=[('Head Coach', 'Head Coach'), ('Offensive Coordinator', 'Offensive Coordinator'), ('Defensive Coordinator', 'Defensive Coordinator'), ('Special Teams Coordinator', 'Special Teams Coordinator')], max_length=50),
        ),
        migrations.AlterField(
            model_name='coach',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coaches', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='conference',
            field=models.CharField(choices=[('AFC', 'AFC'), ('NFC', 'NFC')], max_length=3),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(choices=[('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West')], max_length=5),
        ),
    ]
