# Generated by Django 4.2.29 on 2026-03-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_coach_last_name_alter_coach_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name_plural': 'Coaches'},
        ),
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('city', 'state', 'team_name')},
        ),
    ]
