# Generated by Django 4.2.29 on 2026-03-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_coach_options_team_city_team_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='state',
            field=models.CharField(default='NA', max_length=2),
            preserve_default=False,
        ),
    ]
