# Generated by Django 4.2.29 on 2026-03-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_city_alter_team_state'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('city', 'state', 'team_name'), name='unique_team_id'),
        ),
        migrations.RemoveField(
            model_name='team',
            name='conference',
        ),
        migrations.RemoveField(
            model_name='team',
            name='division',
        ),
    ]
