# Generated by Django 4.2.29 on 2026-04-25 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_team_unique_together_alter_team_team_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_team_id',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='city',
            new_name='conference',
        ),
        migrations.RemoveField(
            model_name='team',
            name='state',
        ),
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.CharField(default='NFC', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coach',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coach',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coach',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
