# Generated by Django 4.2.29 on 2026-04-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_alter_coach_options_remove_team_unique_team_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='primary_color',
            field=models.CharField(default='#1a3d28', max_length=7),
        ),
        migrations.AddField(
            model_name='team',
            name='secondary_color',
            field=models.CharField(default='#f0c040', max_length=7),
        ),
        migrations.AddField(
            model_name='team',
            name='state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='team',
            name='text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
