# Generated by Django 4.2.29 on 2026-05-01 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0005_playerseasonroster_and_more'),
        ('teams', '0007_team_abbreviation_team_city_team_primary_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='coach',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaches', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.CreateModel(
            name='CoachSeasonAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=75)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_assignments', to='teams.coach')),
                ('team_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_assignments', to='seasons.teamseason')),
            ],
            options={
                'ordering': ['team_season__season__year', 'team_season__team__team_name', 'role', 'coach__last_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='coachseasonassignment',
            constraint=models.UniqueConstraint(fields=('coach', 'team_season', 'role'), name='unique_coach_team_season_role'),
        ),
    ]
