# Generated by Django 4.2.29 on 2026-05-07 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_alter_coach_role_alter_coach_team_alter_team_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='conference',
        ),
        migrations.RemoveField(
            model_name='team',
            name='division',
        ),
    ]
