# Generated by Django 4.2.29 on 2026-05-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_remove_team_conference_remove_team_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coach',
            name='college',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coach',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='external_source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='headshot_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='high_school',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
