# Generated by Django 4.2.29 on 2026-03-17 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatType',
            fields=[
                ('stat_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('stat_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSeasonStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.season')),
                ('stat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.stattype')),
            ],
            options={
                'unique_together': {('player', 'season', 'stat_type')},
            },
        ),
    ]
