# Generated by Django 4.2.29 on 2026-05-01 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0005_playerseasonroster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatType',
            fields=[
                ('stat_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PositionStatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=True)),
                ('stat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_mappings', to='stats.stattype')),
            ],
            options={
                'ordering': ['position', 'display_order', 'stat_type__name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerSeasonStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('player_roster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stats', to='seasons.playerseasonroster')),
                ('stat_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_stats', to='stats.stattype')),
            ],
            options={
                'ordering': ['player_roster__team_season__season__year', 'player_roster__player__last_name', 'stat_type__category', 'stat_type__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='positionstattype',
            constraint=models.UniqueConstraint(fields=('position', 'stat_type'), name='unique_position_stat_type'),
        ),
        migrations.AddConstraint(
            model_name='playerseasonstat',
            constraint=models.UniqueConstraint(fields=('player_roster', 'stat_type'), name='unique_stat_per_roster_stat_type'),
        ),
    ]
