# Generated by Django 4.2.29 on 2026-05-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stattype',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterField(
            model_name='positionstattype',
            name='position',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='stattype',
            name='category',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='playerseasonstat',
            index=models.Index(fields=['stat_type', 'value'], name='idx_playerstat_type_value'),
        ),
        migrations.AddIndex(
            model_name='playerseasonstat',
            index=models.Index(fields=['player_roster', 'value'], name='idx_playerstat_roster_value'),
        ),
        migrations.AddIndex(
            model_name='positionstattype',
            index=models.Index(fields=['position', 'is_primary'], name='idx_posstat_pos_primary'),
        ),
        migrations.AddIndex(
            model_name='positionstattype',
            index=models.Index(fields=['position', 'display_order'], name='idx_posstat_pos_order'),
        ),
        migrations.AddIndex(
            model_name='stattype',
            index=models.Index(fields=['category', 'name'], name='idx_stattype_category_name'),
        ),
    ]
