# Generated by Django 4.2.29 on 2026-05-12 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0006_playerseasonroster_idx_roster_teamseason_active_and_more'),
        ('stats', '0002_alter_stattype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerseasonstat',
            name='player_roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stats', to='seasons.playerseasonroster'),
        ),
    ]
