# Generated by Django 4.2.29 on 2026-03-21 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_team_unique_together_alter_team_team_name_and_more'),
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSeason',
            fields=[
                ('team_season_id', models.AutoField(primary_key=True, serialize=False)),
                ('conference', models.CharField(choices=[('AFC', 'AFC'), ('NFC', 'NFC')], max_length=3)),
                ('division', models.CharField(choices=[('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West')], max_length=5)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_seasons', to='seasons.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_seasons', to='teams.team')),
            ],
        ),
        migrations.AddConstraint(
            model_name='teamseason',
            constraint=models.UniqueConstraint(fields=('team', 'season'), name='unique_team_season'),
        ),
    ]
