# Generated by Django 4.2.29 on 2026-04-25 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0002_teamseason_teamseason_unique_team_season'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-year']},
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1920), django.core.validators.MaxValueValidator(2030)]),
        ),
        migrations.DeleteModel(
            name='TeamSeason',
        ),
    ]
