# Generated by Django 4.2.29 on 2026-04-29 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_team_abbreviation_team_city_team_primary_color_and_more'),
        ('seasons', '0003_alter_season_options_alter_season_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSeason',
            fields=[
                ('team_season_id', models.AutoField(primary_key=True, serialize=False)),
                ('conference', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_seasons', to='seasons.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_seasons', to='teams.team')),
            ],
            options={
                'ordering': ['season__year', 'conference', 'division', 'team__team_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='teamseason',
            constraint=models.UniqueConstraint(fields=('team', 'season'), name='unique_team_per_season'),
        ),
    ]
