# Generated by Django 4.2.29 on 2026-04-29 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_delete_teams'),
        ('seasons', '0004_teamseason_teamseason_unique_team_per_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSeasonRoster',
            fields=[
                ('roster_id', models.AutoField(primary_key=True, serialize=False)),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True)),
                ('roster_status', models.CharField(default='Active', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='season_rosters', to='players.player')),
                ('team_season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_rosters', to='seasons.teamseason')),
            ],
            options={
                'ordering': ['team_season__season__year', 'team_season__team__team_name', 'player__last_name', 'player__first_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='playerseasonroster',
            constraint=models.UniqueConstraint(fields=('player', 'team_season'), name='unique_player_per_team_season'),
        ),
    ]
