# Generated by Django 4.2.29 on 2026-05-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0005_playerseasonroster_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='playerseasonroster',
            index=models.Index(fields=['team_season', 'is_active'], name='idx_roster_teamseason_active'),
        ),
        migrations.AddIndex(
            model_name='playerseasonroster',
            index=models.Index(fields=['player', 'is_active'], name='idx_roster_player_active'),
        ),
        migrations.AddIndex(
            model_name='playerseasonroster',
            index=models.Index(fields=['roster_status'], name='idx_roster_status'),
        ),
        migrations.AddIndex(
            model_name='teamseason',
            index=models.Index(fields=['season', 'team'], name='idx_teamseason_season_team'),
        ),
        migrations.AddIndex(
            model_name='teamseason',
            index=models.Index(fields=['conference', 'division'], name='idx_teamseason_conf_div'),
        ),
    ]
